server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=auth-service-route
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=profile-service-route
spring.cloud.gateway.routes[1].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/profiles/**

spring.cloud.gateway.routes[2].id=product-service-route
spring.cloud.gateway.routes[2].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**, /api/v1/merchant/products/**, /api/v1/admin/products/**

spring.cloud.gateway.routes[3].id=recommendation-service-route
spring.cloud.gateway.routes[3].uri=lb://RECOMMENDATION-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/recommendations/**

spring.cloud.gateway.routes[4].id=inventory-service-route
spring.cloud.gateway.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/inventory/**

spring.cloud.gateway.routes[5].id=cart-service-route
spring.cloud.gateway.routes[5].uri=lb://CART-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/cart/**

spring.cloud.gateway.routes[6].id=order-service-route
spring.cloud.gateway.routes[6].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/orders/**, /api/v1/merchant/orders/**, /api/v1/admin/orders/**, /api/v1/returns/**, /api/v1/admin/returns/**

spring.cloud.gateway.routes[7].id=wallet-service-route
spring.cloud.gateway.routes[7].uri=lb://WALLET-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/wallet/**

spring.cloud.gateway.routes[8].id=payment-service-route
spring.cloud.gateway.routes[8].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/payments/**, /api/v1/refunds/**

spring.cloud.gateway.routes[9].id=delivery-service-route
spring.cloud.gateway.routes[9].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/deliveries/**, /api/v1/admin/deliveries/**, /api/v1/agent/deliveries/**

spring.cloud.gateway.routes[10].id=notification-service-route
spring.cloud.gateway.routes[10].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/notifications/**

spring.cloud.gateway.routes[11].id=review-service-route
spring.cloud.gateway.routes[11].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/reviews/**, /api/v1/admin/reviews/**
