package com.eshoppingzone.order.saga.entity;

public enum SagaStatus {
    STARTED,
    INVENTORY_RESERVED,
    PAYMENT_COMPLETED,
    COD_PAYMENT_PENDING,
    INVENTORY_CONFIRMED,
    INVENTORY_CONFIRMATION_FAILED,
    CART_CLEARED,
    CART_CLEAR_FAILED,
    COMPENSATING,
    COMPENSATED,
    PAYMENT_RECONCILIATION_REQUIRED,
    COMPLETED,
    FAILED
}
